version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    env_file:
      - _envs/.env.db
      - _envs/.env.auth
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  cleanbuy:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
    env_file:
      - _envs/.env.db
      - _envs/.env.auth
    ports:
      - "443:443"
    volumes:
      - .:/app

volumes:
  postgres_data:
    driver: local