"""Add message model

Revision ID: 22aea0e14c36
Revises: ddf4572c832d
Create Date: 2024-08-12 20:10:28.947006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22aea0e14c36'
down_revision: Union[str, None] = 'ddf4572c832d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_users_operations_username', table_name='users_operations')
    op.drop_table('users_operations')
    op.drop_table('delivery_options')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('delivery_option', postgresql.ENUM('INCLUDED', 'NOT_INCLUDED', 'NEGOTIABLE', name='deliveryoptiontype'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='delivery_options_pkey')
    )
    op.create_table('users_operations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'BUYER', name='roletype'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('buyer_information_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buyer_information_id'], ['buyer_information.id'], name='users_operations_buyer_information_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='users_operations_pkey')
    )
    op.create_index('ix_users_operations_username', 'users_operations', ['username'], unique=True)
    op.drop_table('messages')
    # ### end Alembic commands ###
