"""add file model to chat

Revision ID: af9e3d62b845
Revises: 5677d18e2d5e
Create Date: 2024-08-18 22:43:20.618168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9e3d62b845'
down_revision: Union[str, None] = '5677d18e2d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('chats_users_chat_id_fkey', 'chats_users', type_='foreignkey')
    op.drop_constraint('chats_users_user_id_fkey', 'chats_users', type_='foreignkey')
    op.create_foreign_key(None, 'chats_users', 'chats', ['chat_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(None, 'chats_users', 'users', ['user_id'], ['id'], onupdate='CASCADE')
    op.add_column('messages', sa.Column('file_id', sa.Integer(), nullable=True))
    op.alter_column('messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'files', ['file_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('messages', 'file_id')
    op.drop_constraint(None, 'chats_users', type_='foreignkey')
    op.drop_constraint(None, 'chats_users', type_='foreignkey')
    op.create_foreign_key('chats_users_user_id_fkey', 'chats_users', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('chats_users_chat_id_fkey', 'chats_users', 'chats', ['chat_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_table('files')
    # ### end Alembic commands ###
