"""update chat models

Revision ID: 5677d18e2d5e
Revises: c5a2e44d0be1
Create Date: 2024-08-16 15:14:00.456278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5677d18e2d5e'
down_revision: Union[str, None] = 'c5a2e44d0be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE chattype AS ENUM ('PERSONAL')")
    op.add_column('chats', sa.Column('chat_type', sa.Enum('PERSONAL', name='chattype'), nullable=False))
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'chat_id')
    op.drop_column('messages', 'sender_id')
    op.drop_column('chats', 'chat_type')
    op.execute("DROP TYPE chattype")
    # ### end Alembic commands ###
